version: '3.7'

services:
  rabbitmq:
    image: localhost:5000/rabbitmq:3-management
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  retrievepath:
    image: localhost:5000/my_rpimage:latest
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - rabbitmq
  processdata:
    image: localhost:5000/my_proimage:latest
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: none
    depends_on:
      - rabbitmq
  plot:
    image: localhost:5000/my_plotimage:latest
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    depends_on:
      - rabbitmq

networks:
  rabbit:
    driver: overlay
    attachable: true

